apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: integration
  name: integration
spec:
  containers:
  - image: integration
    imagePullPolicy: Never
    name: integration
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
